docs: fix docs examples
instantcommerce/next-api-decorators pull request #552
Opened 2023-02-17 01:53 UTC by julianomcl

This PR fixes two usage examples in docs:
- Import `ValidationPipe` in **Basics**
- Template string in **Validation**

2023-02-22 14:57 UTC, leeuwis requested changes
@julianomcl thanks for fixing these! It does seem that one `}` is removed incorrectly, if this is changed it should be good to go 👍

2023-02-22 14:57 UTC, leeuwis commented on website/docs/validation.md
>  }
```suggestion
    return `Location "${body.label}" saved.`;
  }
}
```

2023-02-25 18:43 UTC, julianomcl commented
> @julianomcl thanks for fixing these! It does seem like one `}` is removed incorrectly, if this is changed it should be good to go 👍

@leeuwis Sorry for that. Fixed now!

2023-02-26 11:26 UTC, leeuwis approved these changes

2023-02-26 11:32 UTC, merged